[project]
name = "steamreviewhumor"
version = "0.0.1"
description = "A project analysing humor inn Steam reviews using BERT models."
authors = [
    { name = "Tilmann Diepenbruck", email = "tdiepenb@smail.uni-koeln.de" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "logging>=0.4.9.6",
    "tqdm>=4.67.1",
]
